version: '3.7'

services:

  test-node:
    container_name: test-node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 9999:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    #command: ["npm", "run", "s", "--silent"]
    command: ["npm", "start"] 

